### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by davesmits** [combor/k8s-mongo-labeler-sidecar#14]
When we start the new version we get the following output in the logs and the pod crashes:

```
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by Dimitar-Boychev** [comment]
Hello, I see the same error.
I have extracted the combor/k8s-mongo-labeler-sidecar image and I think that the primary-sidecar executable inside is compiled for ARM.

`#file primary-sidecar

primary-sidecar: ELF 64-bit LSB  executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped
`

**Comment by gldkru** [comment]
How fix it?

**Comment by michaelkorofiverr** [comment]
Any chance this image can be built for AMD64 as well?
