### ISSUE TITLE
Mongo Unauthorised 

### ISSUE THREAD

**Issue by lachy123** [combor/k8s-mongo-labeler-sidecar#3]
My mongodb-replicaset has authentication enabled, but the sidecar doesn't seem to account for it as I am receiving this unauthorised in the sidecar logs 
`time="2019-12-08T22:16:18Z" level=debug msg="Hosts bson.Array[test-auth-test-46-mongodb-replicaset-0.test-auth-test-46-mongodb-replicaset.dev4.svc.cluster.local:27017, test-auth-test-46-mongodb-replicaset-1.test-auth-test-46-mongodb-replicaset.dev4.svc.cluster.local:27017, test-auth-test-46-mongodb-replicaset-2.test-auth-test-46-mongodb-replicaset.dev4.svc.cluster.local:27017]"
time="2019-12-08T22:16:18Z" level=error msg=Unauthorized`
Is there any way to enable the sidecar to access mongo with authentication?

**Comment by lachy123** [comment]
On further inspection, it seems to be unauthorised access to the cluster/pods to change the labels, not authorisation to the mongo @combor  any help would be great

**Comment by combor** [comment]
Labeler is using "in-cluster" authentication from k8s client. I'm guessing that if you provide `ServiceAccount` token that have access to API it should work. Have a look here: https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens

**Comment by lachy123** [comment]
Having a different issue of not finding primary server, but the hosts are printing 
`	if primaryHost, ok := doc.Lookup("primary").StringValueOK(); ok {
		primary := strings.Split(primaryHost, ".")[0]
		if len(primary) != 0 {
			return primary, nil
		}`
Wondering how this searches as my db.isMaster() prints like this 
`rs0:PRIMARY> db.isMaster()
{
	"hosts" : [
		"test-auth-test-51-mongodb-replicaset-0.test-auth-test-51-mongodb-replicaset.dev4.svc.cluster.local:27017",
		"test-auth-test-51-mongodb-replicaset-1.test-auth-test-51-mongodb-replicaset.dev4.svc.cluster.local:27017",
		"test-auth-test-51-mongodb-replicaset-2.test-auth-test-51-mongodb-replicaset.dev4.svc.cluster.local:27017"
	],
	"setName" : "rs0",
	"setVersion" : 3,
	"ismaster" : true,
	"secondary" : false,
	"primary" : "test-auth-test-51-mongodb-replicaset-0.test-auth-test-51-mongodb-replicaset.dev4.svc.cluster.local:27017",
	"me" : "test-auth-test-51-mongodb-replicaset-0.test-auth-test-51-mongodb-replicaset.dev4.svc.cluster.local:27017",
	"electionId" : ObjectId("7fffffff0000000000000006"),
	"lastWrite" : {`

**Comment by lachy123** [comment]
Ahh I see thanks for the help

**Comment by combor** [comment]
I'll close this now.
