### ISSUE TITLE
SSL authentication

### ISSUE THREAD

**Issue by lachy123** [combor/k8s-mongo-labeler-sidecar#4]
After enabling SSL in my mongodb i started receiving these logs, 

`time="2019-12-19T21:53:09Z" level=info msg="Setting logging level to debug"
time="2019-12-19T21:53:14Z" level=error msg="connection(localhost:27017[-1]) unable to decode message length: EOF"`

Not sure if anything else needs to be done after enabling ssl? or if i've just done it wrong?

**Comment by combor** [comment]
I have never tested SSL TBH. It would be good to check what mongo-go-driver can offer us: https://github.com/combor/k8s-mongo-labeler-sidecar/blob/master/main.go#L167

**Comment by lachy123** [comment]
sidecar works with preferSSL but not requireSSL

**Comment by dgdevops** [comment]
Hello Guys,
Bit late to the party but I am facing the same issue but I need to use "requireTLS" option to explicitly allow TLS-only connections.
@combor, is there any chance to have the TLS option added?

Thanks a lot

**Comment by ChuckNoxis** [comment]
Hello @combor, thanks for you work :)

I would like to know as @dgdevops, if TLS implementation is a feature you will implement in the near future ? I also would like to use `requireTLS` instead of `preferTLS`.
Thanks :)
