### ISSUE TITLE
issues connecting to mongo pod

### ISSUE THREAD

**Issue by korenlev** [combor/k8s-mongo-labeler-sidecar#5]
1. ssl connection not supported , will try to contribute this option
2. can u confirm please:  with this labeling solution SECONDARIES can only sync to PRIMARY as there is no SECONDARY to SECONDARY communication possible (service-pod in primary:"false" so selector don't match) - correct ?

**Comment by combor** [comment]
Hi, this solution has nothing to do with mongo synchronization. It only adds labels on top of pods so you can use them for somthing fun like LB filtering etc.

**Comment by combor** [comment]
This issue is not very active. I'll close it now.
